<? 
$title="Авторизация"; 
$color="#aaaaff"; 
 
$pass=$HTTP_POST_VARS["pass"]; 
$login=$HTTP_POST_VARS["login"]; 
 
include("connect.phtml"); 
 
$strSQL1="SELECT * FROM customers WHERE login='".$login. 
 	"' AND pass='".$pass."'"; 
$result1=mysql_query($strSQL1)   	or die("Не могу выполнить запрос!"); if($row=mysql_fetch_array($result1))  
{ 
  $start=session_start();   session_register("log");  
  $HTTP_SESSION_VARS["log"]=$row["fam"]." ".$row["im"];   session_register("id");  
  $HTTP_SESSION_VARS["id"]=$row["id_cust"]; 
  $message="<tr><td bgcolor='#66cc66' align='center'> 
   <b>Вы успешно авторизованы</b></td></tr>"; 
  $success=true; 
} else 
{ 
  $message="<tr><td bgcolor='#ff9999' align='center'> 
  <b>Таких логина/ пароля не существует!!!</b></td></tr>"; 
} 
mysql_close(); 
 
if($success) 
{ 
   include ("cabinet.phtml"); 
} else {    include("header.phtml");    print $message;    include("footer.phtml"); 
} 
?>