<? 
$title="Личный кабинет"; 
$color="#aaaaff"; 
 
$log=$HTTP_SESSION_VARS["log"]; 
$id=$HTTP_SESSION_VARS["id"]; 
 
if(!isset($log)) 
{ 
  $success=false; 
  $message="<tr><td bgcolor='#ff9999' align='center'> 
     <b>Вы не авторизованы!!!</b></td></tr>"; 
} else  
  $success=true; 
 
include("header.phtml"); print $message; 
 
if($success) 
{ 
include("connect.phtml"); 
$strSQL="SELECT * FROM customers WHERE id_cust='".$id."'"; 
$result=mysql_query($strSQL)  
 	or die("Не могу выполнить запрос!"); if($row=mysql_fetch_array($result))  
{ 
?> 
<form action=change.phtml method=post> 
<tr><td> 
<h2>Ваши личные данные</h2> 
<table border="0" width="100%" align="right" > 
 <tr><td align="right"><i>Фамилия: </i></td><td> 
 <input type=text name=fam value="<?print $row["fam"]?>"></td> 
 <td align="right"><i>Имя: </i></td><td> 
 <input type=text name=im value="<?print $row["im"]?>"></td> 
 </tr> 
 <tr><td align="right"><i>Адрес: </i></td><td> 
 <input type=text name=addr value="<?print $row["addr"]?>"></td> 
 <td align="right"><i>E-mail: </i></td><td> 
 <input type=text name=mail value="<?print $row["mail"]?>"></td> 
 </tr> 
 <tr><td align="right" colspan=3><i> 
 <input type="checkbox" value="1" name="subscribe"  
 <? if($row["subscribe"]==1) print "checked"; ?> > 
 <tr><td align="center" colspan="4"> 
 <input type="submit" value="сохранить изменения"></td></tr>  
</table> 
</form> 
</td></tr> 
<tr><td> 
<h2>Ваши заказы</h2> 
<? 
$strSQL1="SELECT id_order, date_ord FROM orders  
 	WHERE id_cust='".$id."' ORDER BY date_ord DESC"; 
$result1=mysql_query($strSQL1)   	or die("Не могу выполнить запрос1!"); while($row1=mysql_fetch_array($result1)) 
{ 
  $order=$row1["id_order"]; 
  $strSQL2="SELECT author, name_book, pages,       price, kolvo, id_order, books.id_book  
     FROM books,   order_books WHERE         books.id_book=order_books.id_book       and id_order='".$order."'";   $result2=mysql_query($strSQL2)  
 	or die("Не могу выполнить запрос2!"); 
  ?> 
  <tr><td> 
  <hr> 
  <b>Заказ № <?=$order?> от <?=$row1["date_ord"]?><br></b> 
  <table border="1" width="100%" align="right" > 
  <tr><td align="right" width="20%"><i>Автор: </i></td> 
  <td align="right" width="50%"><i>Название: </i></td> 
  <td align="right" width="15%"><i>Цена: </i></td> 
  <td align="right" width="15%"><i>Количество: </i></td></tr> 
  <?   $sum=0; 
  while($row2=mysql_fetch_array($result2))  
  { 
  ?> 
    <tr> 
     <td><?print $row2["author"];?></td> 
     <td><b><?print $row2["name_book"];?></b></td> 
     <td><?print $row2["price"];?></td> 
     <td><?print $row2["kolvo"];?></td>  
    </tr> 
  <?$sum=$sum+$row2["price"]*$row2["kolvo"]; 
  } 
  $strSQL3="SELECT name_cat FROM categories, orders      WHERE categories.id_cat=orders.bonus AND    
          id_order='".$order."'";   $result3=mysql_query($strSQL3)          or die("Не могу выполнить запрос3!");   if($row3=mysql_fetch_array($result3))   {?> 
  <tr> 
    <td colspan=2>Бесплатный каталог по теме <b> 
    <?print $row3["name_cat"];?></b></td> 
    <td>0</td> 
    <td>1</td> 
   </tr> 
  <?} 
  ?> 
  <tr><td></td><td align="right"><i>ИТОГО: </i></td>    <td><?print $sum;?></td><td></td></tr> 
  </table> 
  </td></tr> 
 
  <? 
  } } 
mysql_close(); 
}  
include("footer.phtml"); 
?> 