<? header("Cache-control: no-cache"); 
 
$id_bask=$HTTP_COOKIE_VARS["id_bask"]; 
if (! isset($id_bask)) 
{ 
  	$uniq_ID=uniqid("ID");  
 	setcookie("id_bask", $uniq_ID, time()+60*60*24*14);  
     // создадим ключик 
} else setcookie("id_bask", $id_bask, time()+60*60*24*14);  
// пересоздадим ключик с тем же значением 
 
?> 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN"> 
 
<html> 
<head> 
 	<title>КНИЖНЫЙ МАГАЗИН</title> 
</head> 
 
<body background="EULA.jpg" style="background-repeat:repeat-y" leftmargin="130" rightmargin="5" bgProperties=fixed> <table border="0" align="right" width="90%" cellpadding="0" cellspacing="0"> 
<tr><td> 
 
<table border="0" align="right" width="100%" > 
<tr> 
<td align="center" bgcolor="#cccccc"> 
<form action="auto.phtml" method="post"> 
<table> 
<tr><td align="right"><font size=-2>Логин:</font></td> <td align="left"><input type=text style="width:60; height:20;" name=login></td></tr> 
<tr><td align="right"><font size=-2>Пароль:</font></td> 
<td align="left"><input type=password style="width:60; height:20;" name=pass> 
<input type=submit value=ok style="height:20;"></td></tr> 
</table> 
<b><small> 
<?  if(isset($HTTP_SESSION_VARS["log"])) 
{ 
   print $HTTP_SESSION_VARS["log"]; 
   print "<br><a href='cabinet.phtml'>Личный кабинет</a>"; }  
?> 
</small></b></td> 
</form> 
<td colspan="4" align="center" bgcolor="#ccccff"> 
<font face="Arial" size="+3"><i><b>Книжный магазин</b></i></font></td></tr> 
<tr><td align="center" bgcolor="#aaddff" width="20%"> 
<a href="catalog.phtml"><b>Каталог</b></a></td>  
<td align="center" bgcolor="#ddaaff" width="20%"> 
<a href="basket.phtml"><b>Корзина</b></a></td> 	 <td align="center" bgcolor="#aaaaff" width="20%"> 
<a href="reg.phtml"><b>Регистрация</b></a></td>  <td align="center" bgcolor="#ffaaff" width="20%"> 
<a href="order.phtml"><b>Заказ</b></a></td>  	 <td align="center" bgcolor="#aaffee" width="20%"> 
<a href="exit.phtml"><b>Выход</b></a></td>  	 
</tr> 
</table> 
</td></tr> 
<tr><td align="center" bgcolor=<?print $color?>><font face="Arial" size="+2"> 
<i><?print $title?></i></font><br> 
</td></tr> 