<? 
$id_bask=$HTTP_COOKIE_VARS["id_bask"]; 
 
$title="Ваш заказ"; 
$color="#ffaaff"; include("header.phtml"); include("connect.phtml"); 
 
$strSQL1="SELECT COUNT(*) as count FROM basket_books  
     WHERE id_bask='".$id_bask."'"; 
$result1=mysql_query($strSQL1)  
     or die("Не могу выполнить запрос2!"); 
$row=mysql_fetch_array($result1); 
if($row["count"]==0) 
 
{ 
?> 
<tr><td bgcolor='#ff9999' align='center'> 
  <b>Ваша корзина пуста!</b></td></tr> 
<? } else 
{ 
$strSQL1="SELECT image, author, name_book, pages, price, kolvo,  
   id_bask, books.id_book FROM books, basket_books    WHERE books.id_book=basket_books.id_book AND      id_bask='".$id_bask."'"; 
$result1=mysql_query($strSQL1)     or die("Не могу выполнить запрос2!"); 
 
?> 
<tr><td> 
<table border="1" width="100%" align="right" > 
<tr><td align="right"><i>Автор: </i></td> 
<td align="right"><i>Название: </i></td> 
<td align="right"><i>Цена: </i></td> 
<td align="right"><i>Количество: </i></td></tr> 
<? $sum=0; 
while($row=mysql_fetch_array($result1))  
{ 
?> 
  <tr> 
   <td><?print $row["author"];?></td> 
   <td><b><?print $row["name_book"];?></b></td>    <td><?print $row["price"];?></td> 
   <td><?print $row["kolvo"];?></td>  
  </tr> 
<? 
  $sum=$sum+$row["price"]*$row["kolvo"]; 
} 
?> 
<tr><td></td><td align="right"><i>ИТОГО: </i></td> <td><?print $sum;?></td><td></td></tr> 
</table> 
<tr><td><br><b>Способ доставки:</b>  
  <input type="radio" value=1 name="dostavka" checked>     почта России 
  <input type="radio" value=2 name="dostavka"> курьер 
  <input type="radio" value=3 name="dostavka"> самовывоз 
</td><tr> 
<tr><td>Прислать бесплатный каталог по теме: 
  <select name="bonus"> 
  <option value="0"> 
  <? $strSQL1="SELECT * FROM categories";      $result1=mysql_query($strSQL1)          or die("Не могу выполнить запрос!");      while($row=mysql_fetch_array($result1)) 
     {?> 
      <option value="<? print $row["id_cat"]?>">  
      <? print $row["name_cat"];      } 
  ?>  
</td><tr> 
<tr><td><center><a href=doorder.phtml> 
   <b>Отправить заказ</b></a></center></td></tr> 
<? } 
include("footer.phtml"); 
?> 