<? 
$title="Регистрация"; 
$color="#aaaaff"; 
 
$fam=$HTTP_POST_VARS["fam"]; 
$im=$HTTP_POST_VARS["im"]; 
$addr=$HTTP_POST_VARS["addr"]; 
$mail=$HTTP_POST_VARS["mail"]; 
$pass=$HTTP_POST_VARS["pass"]; 
$pass2=$HTTP_POST_VARS["pass2"]; 
$login=$HTTP_POST_VARS["login"]; 
$type=$HTTP_POST_VARS["type"]; 
$subscribe=$HTTP_POST_VARS["subscribe"]; 
 
include("connect.phtml"); 
if($type==1) 
{  
if($fam!="" && $im!="" && $addr!="" && $mail!="" && $login!=""   
            && $pass!="" && $pass2!="") 
{ 
  if($pass!=$pass2) 
  { 
    $message="<tr><td bgcolor='#ff9999' align='center'><b>  
    Поля пароля и повтора пароля не совпадают!!!</b></td></tr>"; 
  }   else  
  { 
    $strSQL1="SELECT id_cust FROM customers  
       WHERE login='".$login."'"; 
    $result1=mysql_query($strSQL1)         or die("Не могу выполнить запрос!"); 
    if($row=mysql_fetch_array($result1))  
 	{ 
 	   $message="<tr><td bgcolor='#ff9999' align='center'>          <b>Такой логин уже существует!!! Выберите другой              логин</b></td></tr>"; 
     } 
 	else 
 	{ 
 	  $strSQL1="INSERT INTO customers  
         (fam, im, addr, mail, login, pass, subscribe)   
         VALUES('".$fam."','".$im."','".$addr."','".$mail. 
          "','".$login."','".$pass."','".$subscribe."')"; 
 	  $result1=mysql_query($strSQL1)            or die("Не могу выполнить запрос!"); 
 	 	$message="<tr><td bgcolor='#66cc66' align='center'> 
             <b>Вы успешно зарегистрированы</b></td></tr>"; 
 	  $success=true; 
 	} 
   }  } else  
  $message="<tr><td bgcolor='#ff9999' align='center'> 
     <b>Не все поля заполнены!!!</b></td></tr>"; 
}  
include("header.phtml"); print $message; 
 
if(!$success) 
{ 
?> 
 
<form action=reg.phtml method=post> 
<tr><td align="center"> 
<small>Звездочками отмечены обязательные поля</small> 
<table border="0" width="100%" align="right" > 
  <tr><td align="right" width="50%"><i>Фамилия: </i></td><td> 
  <input type=text name=fam value="<?print $fam?>">*</td></tr> 
  <tr><td align="right"><i>Имя: </i></td><td> 
  <input type=text name=im value="<?print $im?>">*</td></tr> 
  <tr><td align="right"><i>Адрес: </i></td><td> 
  <input type=text name=addr value="<?print $addr?>">*</td></tr> 
  <tr><td align="right"><i>E-mail: </i></td><td> 
  <input type=text name=mail value="<?print $mail?>">*</td></tr> 
  <tr><td align="right"><i>Логин: </i></td><td> 
  <input type=text name=login value="<?print $login?>">*</td> 
  </tr> 
  <tr><td align="right"><i>Пароль: </i></td><td> 
  <input type=password name=pass value="">*</td></tr> 
  <tr><td align="right"><i>Повтор пароля: </i></td><td> 
  <input type=password name=pass2 value="">*</td></tr>  
  <tr><td></td><td> 
   <input type=hidden value=1 name=type> 
   <tr><td align="right"></td><td> 
    <input type=submit value="отправить"></td></tr>  
</table> 
</form> 
</td></tr> 
<? mysql_close(); 
} 
include("footer.phtml"); 
?> 